schema_version: 1

context:
  version: "2.70.46"

package:
  name: cdk8s
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/cdk8s/cdk8s-${{ version }}.tar.gz
  sha256: d4f86ff6518b267f7ba1db6b0504be150e34e591da2f2b015de9bf424c2c89d6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=75.3.2
    - python-build >=1.3.0
    - pip
  run:
    - python >=${{ python_min }}
    - constructs >=10.0.0,<11.0.0
    - python-jsii >=1.126.0,<2.0.0
    - publication >=0.0.3
    - typeguard ==2.13.3

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - cdk8s
      pip_check: true

about:
  summary: This is the core library of Cloud Development Kit (CDK) for Kubernetes (cdk8s). cdk8s apps synthesize into standard Kubernetes manifests which can be applied to any Kubernetes cluster.
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  homepage: https://github.com/cdk8s-team/cdk8s-core.git
  repository: https://github.com/cdk8s-team/cdk8s-core.git

extra:
  recipe-maintainers:
    - janjagusch
